### PR TITLE
e2e: initial commit of e2e tests

### PR DESCRIPTION
**Pull request by jbpratt**
# What is being added?
_Is this a fix for a bug?  What's the bug?  Is this a new feature? Please describe it. Is this just a small typo fix?  That's fine too!_

new tests

move e2e tests over from https://github.com/openshift/osde2e/pull/1260 and refactor to not depend on osde2e

## Checklist before requesting review

- [x] I have tested this locally
- [ ] I have included unit tests
- [ ] I have updated any corresponding documentation

## Steps To Manually Test

The tests can be ran locally against a cluster after modifying the test files slightly then ran with OCM_ENVIRONMENT=stage CLUSTER_ID=<cluster id> ginkgo run ./osde2e/ -v

```
diff --git a/osde2e/managed_node_metadata_operator_runner_test.go b/osde2e/managed_node_metadata_operator_runner_test.go
index 929c024..1240e3c 100644
--- a/osde2e/managed_node_metadata_operator_runner_test.go
+++ b/osde2e/managed_node_metadata_operator_runner_test.go
@@ -11,18 +11,11 @@ import (
        . "github.com/onsi/gomega"
 )

-const (
-       testResultsDirectory = "/test-run-results"
-       jUnitOutputFilename  = "junit-example-addon.xml"
-)
-
 // Test entrypoint. osde2e runs this as a test suite on test pod.
 func TestManagedNodeMetadataOperator(t *testing.T) {
        RegisterFailHandler(Fail)

-       suiteConfig, reporterConfig := GinkgoConfiguration()
-       reporterConfig.JUnitReport = filepath.Join(testResultsDirectory, jUnitOutputFilename)
-       RunSpecs(t, "Managed Node Metadata Operator", suiteConfig, reporterConfig)
+       RunSpecs(t, "Managed Node Metadata Operator")

 }
```

Ref [SDCICD-930](https://issues.redhat.com//browse/SDCICD-930)

### CODE REVIEW

**Review by ryankwilliams — COMMENTED** [review]
Just one small suggestion, other than that. Looks good to me @jbpratt

**Comment by AlexVulaj** [comment]
I was able to run these tests against a staging cluster and all seems to have passed.
```
$ OCM_ENVIRONMENT=stage CLUSTER_ID=23oi848sgb90jjkb5pmtfnu0ta976l7c ginkgo run ./osde2e/ -v
=== RUN   TestManagedNodeMetadataOperator
Running Suite: Managed Node Metadata Operator - /Users/alexvulaj/Workspace/managed-node-metadata-operator/osde2e
================================================================================================================
Random Seed: 1684261303

Will run 6 of 6 specs
I0516 14:21:45.456388   59166 request.go:682] Waited for 1.049942s due to client-side throttling, not priority and fairness, request: GET:https://api.stage.backplane.openshift.com/backplane/cluster/23oi848sgb90jjkb5pmtfnu0ta976l7c/apis/coordination.k8s.io/v1?timeout=32s
••••••

Ran 6 of 6 Specs in 300.323 seconds
SUCCESS! -- 6 Passed | 0 Failed | 0 Pending | 0 Skipped
--- PASS: TestManagedNodeMetadataOperator (300.32s)
PASS

Ginkgo ran 1 suite in 5m37.745977625s
Test Suite Passed
```

**Pull request merged**
